import { test, expect } from '@playwright/test';

// Functional click-through + visual baseline — the real-browser half of the gate (catches what
// jsdom can't: JS-rendered state, layout, colour/contrast via the screenshot). Runs against the
// good fixture by default; against UIV_TARGET when set. Per-feature specs generated by the
// engineer for real screens live alongside the feature, not here — this is the gate's self-test.

const NAV = ['nav-explorer', 'nav-inspector', 'nav-settings'] as const;

test('every primary nav link navigates to a visible, real section ("links up")', async ({ page }) => {
  await page.goto('/');
  for (const id of NAV) {
    const link = page.getByTestId(id);
    await expect(link, `nav link ${id} should exist`).toBeVisible();
    const href = await link.getAttribute('href');
    expect(href, `nav link ${id} should have an href`).toBeTruthy();
    const targetId = (href ?? '').replace(/^#/, '');
    // The "links up" assertion: the in-page target the nav points to must actually exist & be visible.
    await link.click();
    await expect(
      page.locator(`#${targetId}`),
      `nav target #${targetId} must exist and be visible`,
    ).toBeVisible();
  }
});

test('screen matches its visual baseline (8-state baselines for real components)', async ({ page }) => {
  await page.goto('/');
  // For a single static fixture we snapshot the full page. Real components capture the 8 named
  // states (default/hover/focus/active/disabled/loading/empty/error) per testing-ts.md.
  await expect(page).toHaveScreenshot('graph-explorer--default.png', { fullPage: true });
});
