"""BE-SDK-1 OpenAPI 3.1 emitter (ADR-006 SS2, Implementation Hints).

Wraps CE-READ-1/CE-WRITE-1 as the *client-facing* graph surface -- one
``/graph/{kind}`` path per generated class plus the apply-operations
passthrough (``contracts.md`` SS BE-SDK-1(b), cited only). Built as a plain
Python dict, dumped with ``yaml.safe_dump(sort_keys=True)`` rather than a
Jinja2 template: nested YAML indentation is fragile to hand-template, and
``sort_keys`` gives byte-identical output for free (AC-1) regardless of
dict insertion order.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from weave_backend.sdkgen.ir import IRField, SdkModel

_SCALAR_OPENAPI: dict[str, dict[str, object]] = {
    "string": {"type": "string"},
    "number": {"type": "number"},
    "boolean": {"type": "boolean"},
}

_HEADER = (
    "# GENERATED by BE-SDK-1 (Weave Build Engine) -- DO NOT EDIT.\n"
    "# generated_at: {{GENERATED_AT}}\n"
)


def _property_schema(field: IRField) -> dict[str, object]:
    if field.ts_type in _SCALAR_OPENAPI:
        base = dict(_SCALAR_OPENAPI[field.ts_type])
    elif field.ts_type.startswith("'"):
        values = [part.strip().strip("'") for part in field.ts_type.split(" | ")]
        base = {"type": "string", "enum": values}
    else:
        # ponytail: reference/union types collapse to a generic object in
        # the OpenAPI projection -- no AC/test requires per-field OpenAPI
        # fidelity (only AC-7's structural lint), and the mapping table's
        # AC-3 no-fallback rule is scoped to the SHACL->IR mapper, not this
        # client-facing re-projection. Upgrade to $ref component schemas
        # if a real OpenAPI consumer needs it.
        base = {"type": "object"}
    if field.is_list:
        return {"type": "array", "items": base}
    return base


def _class_schema_and_path(
    cls_name: str, fields: list[IRField]
) -> tuple[dict[str, object], dict[str, object]]:
    properties = {f.name: _property_schema(f) for f in fields}
    required = sorted(f.name for f in fields if not f.optional)
    schema: dict[str, object] = {"type": "object", "properties": properties}
    if required:
        schema["required"] = required
    path: dict[str, object] = {
        "get": {
            "operationId": f"list{cls_name}",
            "responses": {
                "200": {
                    "description": f"{cls_name} instances",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {"$ref": f"#/components/schemas/{cls_name}"},
                            }
                        }
                    },
                }
            },
        }
    }
    return schema, path


def build_openapi_doc(ir: SdkModel) -> dict[str, object]:
    schemas: dict[str, object] = {}
    paths: dict[str, object] = {}
    for cls in ir.classes:
        schema, path = _class_schema_and_path(cls.name, cls.fields)
        schemas[cls.name] = schema
        paths[f"/graph/{cls.name.lower()}"] = path
    paths["/graph/apply"] = {
        "post": {
            "operationId": "applyOperations",
            "description": "CE-WRITE-1 apply-operations passthrough",
            "responses": {"200": {"description": "Applied"}},
        }
    }
    return {
        "openapi": "3.1.0",
        "info": {"title": "Weave Generated SDK", "version": ir.pin.version_iri},
        "paths": paths,
        "components": {"schemas": schemas},
    }


def emit_openapi(ir: SdkModel, into: Path) -> None:
    into.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(build_openapi_doc(ir), sort_keys=True, default_flow_style=False)
    (into / "openapi.yaml").write_text(_HEADER + body)
