// GENERATED by BE-SDK-1 (Weave Build Engine) -- DO NOT EDIT.
// generated_at: {{GENERATED_AT}}
// ce_version: urn:weave:ce:v1

import { NotExecutableUntilPostV1 } from "./errors";

export interface Process {
  description?: string;
  label: string;
  tags: string[];
}

export class WeaveClient {
  calculateTotal(amount: number, currency?: string): number {
    throw new NotExecutableUntilPostV1("weave:calculateTotal");
  }

  countItems(label: string): number {
    throw new NotExecutableUntilPostV1("weave:countItems");
  }

}

export const themeColor: Record<string, unknown> = {"bg": "#0a0a0a"};
export const themeTypography: Record<string, unknown> = {};
export const themeSpacing: Record<string, unknown> = {};
export const themeRadius: Record<string, unknown> = {};
export const themeExtensions: Record<string, unknown> = {};