# GENERATED by BE-SDK-1 (Weave Build Engine) -- DO NOT EDIT.
# generated_at: {{GENERATED_AT}}
# ce_version: urn:weave:ce:v1

from __future__ import annotations

from pydantic import BaseModel

from .errors import NotExecutableUntilPostV1

class WeaveClient:
    def calculateTotal(
        self, amount: float, currency: str | None = None    ) -> float:
        raise NotExecutableUntilPostV1("weave:calculateTotal")

    def countItems(
        self, label: str    ) -> int:
        raise NotExecutableUntilPostV1("weave:countItems")

