# GENERATED by BE-SDK-1 (Weave Build Engine) -- DO NOT EDIT.
# generated_at: {{GENERATED_AT}}
# ce_version: urn:weave:ce:v1

from __future__ import annotations

from datetime import date, datetime  # noqa: F401 -- referenced by mapped field types, not every model uses every import
from decimal import Decimal  # noqa: F401
from typing import Literal  # noqa: F401

from pydantic import AnyUrl, BaseModel, Field  # noqa: F401

class Process(BaseModel):
    description: str | None = None
    label: str
    tags: list[str] = Field(min_length=1)

