# GENERATED by BE-SDK-1 (Weave Build Engine) -- DO NOT EDIT.
# generated_at: {{GENERATED_AT}}

from __future__ import annotations

THEME_COLOR: dict[str, object] = {"bg": "#0a0a0a"}
THEME_TYPOGRAPHY: dict[str, object] = {}
THEME_SPACING: dict[str, object] = {}
THEME_RADIUS: dict[str, object] = {}
THEME_EXTENSIONS: dict[str, object] = {}