/* global React, Icon, Avatar, Btn, FIXTURES */
const { useState: uS_sp } = React;

const SPECS = [
  { id:'SPEC-018', title:'Motor Fast-Track Claims Service', status:'in-review', updated:'9m ago', author:'Spec Agent', domains:['Claims','Customer'], summary:'Auto-adjudicate motor claims under £2,500 with no fraud signal. Routes exceptions to humans, full audit.', phase:'HITL review' },
  { id:'SPEC-017', title:'Edge cache for portal-bff',         status:'draft',     updated:'2h ago', author:'Spec Agent', domains:['Customer','Platform'], summary:'Reduce portal-bff p95 from 240ms → <80ms by adding a shared edge cache for portfolio and policy DTOs.', phase:'Drafting' },
  { id:'SPEC-016', title:'Fraud-scorer v3.2 schema migration', status:'approved',  updated:'1d ago', author:'Maya Patel', domains:['Claims'],            summary:'Schema bump for fraud-scorer adding contextual risk signals. Two-phase migration with shadowing.', phase:'Implementing' },
  { id:'SPEC-015', title:'Lending Snowflake ingestion expansion', status:'approved', updated:'4d ago', author:'Chris Okafor', domains:['Lending'],         summary:'Add servicing & payoff event streams to existing Snowflake pipeline.', phase:'Implementing' },
  { id:'SPEC-014', title:'Customer identity unification (KYC dedup)', status:'changes-requested', updated:'5d ago', author:'Spec Agent', domains:['Customer'], summary:'Merge identity-svc and kyc-adapter dedup paths. Compliance flagged scope of profile mutation.', phase:'Revising' },
  { id:'SPEC-013', title:'Auto-renewal nudges for low-engagement policyholders', status:'rejected', updated:'8d ago', author:'Spec Agent', domains:['Policy','Customer'], summary:'Marketing-led nudge campaign — rejected as outside platform remit.', phase:'Closed' },
];

const STATUS_TONE = {
  'in-review': { bg:'rgba(59,130,246,0.15)', c:'#BFDBFE', l:'In HITL review' },
  'draft':     { bg:'rgba(148,163,184,0.15)', c:'#CBD5E1', l:'Draft' },
  'approved':  { bg:'rgba(16,185,129,0.15)',  c:'#A7F3D0', l:'Approved' },
  'changes-requested': { bg:'rgba(245,158,11,0.15)', c:'#FCD34D', l:'Changes requested' },
  'rejected':  { bg:'rgba(239,68,68,0.15)',   c:'#FCA5A5', l:'Rejected' },
};

const SpecsScreen = ({ navigate }) => {
  const [selected, setSelected] = uS_sp(SPECS[0].id);
  const [filter, setFilter] = uS_sp('All');
  const filters = ['All','Drafts','In review','Approved','Changes','Rejected'];
  const list = SPECS.filter(s => {
    if (filter === 'All') return true;
    if (filter === 'Drafts') return s.status === 'draft';
    if (filter === 'In review') return s.status === 'in-review';
    if (filter === 'Approved') return s.status === 'approved';
    if (filter === 'Changes') return s.status === 'changes-requested';
    if (filter === 'Rejected') return s.status === 'rejected';
    return true;
  });
  const spec = SPECS.find(s => s.id === selected);

  return (
    <div className="page-enter" style={{ padding: '20px 24px', maxWidth: 1480, margin: '0 auto' }}>
      <window.PageHeader
        eyebrow="Spec library"
        icon="doc"
        title="Specs"
        subtitle={`${SPECS.length} specs across draft, review, approved, and closed states`}
        role="The library of every brief, PRD, and tech spec generated by the Spec Agent — across all projects and all stages."
        purpose="Browse, open, edit, or approve specs. Each spec is the contract between an idea and an executable project."
        contributes="The artefact layer between Snappy (where specs are created) and Change Mgmt (where they're sequenced into projects)."
        actions={<Btn variant="primary" icon="sparkle" onClick={() => navigate('/snappy')}>New Snappy Request</Btn>}
      />

      <div style={{ display:'flex', gap: 6, marginBottom: 14 }}>
        {filters.map(f => (
          <button key={f} className={`tab ${filter === f ? 'active' : ''}`} onClick={() => setFilter(f)}>{f}</button>
        ))}
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'420px 1fr', gap: 14, alignItems:'flex-start' }}>
        <div className="card" style={{ padding: 0, overflow:'hidden' }}>
          {list.map((s, i) => {
            const tone = STATUS_TONE[s.status];
            const active = selected === s.id;
            return (
              <div key={s.id} onClick={() => setSelected(s.id)}
                style={{
                  padding: '12px 14px',
                  borderTop: i ? '1px solid var(--line-soft)' : 'none',
                  background: active ? 'rgba(59,130,246,0.08)' : 'transparent',
                  borderLeft: active ? '2px solid var(--blue)' : '2px solid transparent',
                  cursor:'pointer',
                }}>
                <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom: 4 }}>
                  <span className="mono" style={{ fontSize: 10.5, color:'var(--text-mute)' }}>{s.id}</span>
                  <span style={{ fontSize: 9.5, fontWeight:600, padding:'1px 6px', borderRadius:3, background: tone.bg, color: tone.c, textTransform:'uppercase', letterSpacing:'0.05em' }}>{tone.l}</span>
                </div>
                <div style={{ fontSize: 13, fontWeight: 500, marginBottom: 4 }}>{s.title}</div>
                <div style={{ fontSize: 11, color:'var(--text-mute)' }}>{s.author} · {s.updated}</div>
              </div>
            );
          })}
        </div>

        {spec && <SpecEditor spec={spec} navigate={navigate}/>}
      </div>
    </div>
  );
};

const SpecEditor = ({ spec, navigate }) => {
  const [tab, setTab] = uS_sp('Brief');
  const tabs = ['Brief','PRD','Tech spec','Decisions','History'];
  const tone = STATUS_TONE[spec.status];

  return (
    <div className="card" style={{ padding: 0, overflow:'hidden' }}>
      <div style={{ padding: '14px 18px', borderBottom:'1px solid var(--line)' }}>
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>
          <div>
            <div style={{ display:'flex', alignItems:'center', gap: 8, marginBottom: 4 }}>
              <span className="mono" style={{ fontSize: 11, color:'var(--text-mute)' }}>{spec.id}</span>
              <span style={{ fontSize: 9.5, fontWeight:600, padding:'1px 6px', borderRadius:3, background: tone.bg, color: tone.c, textTransform:'uppercase', letterSpacing:'0.05em' }}>{tone.l}</span>
              {spec.domains.map(d => <span key={d} className="chip">{d}</span>)}
            </div>
            <h2 style={{ margin: 0, fontSize: 18, fontWeight: 600 }}>{spec.title}</h2>
            <div style={{ fontSize: 11.5, color:'var(--text-mute)', marginTop: 4 }}>by {spec.author} · updated {spec.updated} · phase: {spec.phase}</div>
          </div>
          <div style={{ display:'flex', gap: 6 }}>
            {spec.status === 'in-review' && <>
              <Btn icon="check" variant="primary" onClick={() => navigate('/change')}>Approve</Btn>
              <Btn>Request changes</Btn>
            </>}
            {spec.status === 'draft' && <Btn variant="primary" icon="sparkle">Submit for review</Btn>}
            {spec.status === 'approved' && <Btn icon="cube" onClick={() => navigate('/project/csp-v2/dashboard')}>Open project</Btn>}
          </div>
        </div>
        <div style={{ display:'flex', gap: 2, marginTop: 12 }}>
          {tabs.map(t => (
            <button key={t} className={`tab ${tab === t ? 'active' : ''}`} onClick={() => setTab(t)}>{t}</button>
          ))}
        </div>
      </div>

      <div style={{ padding: 18, minHeight: 400 }}>
        {tab === 'Brief' && <BriefEditor spec={spec}/>}
        {tab === 'PRD' && <PRDEditor/>}
        {tab === 'Tech spec' && <TechEditor/>}
        {tab === 'Decisions' && <DecisionsList/>}
        {tab === 'History' && <HistoryList/>}
      </div>
    </div>
  );
};

const SpField = ({ label, children }) => (
  <div style={{ marginBottom: 14 }}>
    <div className="h-eyebrow" style={{ marginBottom: 6 }}>{label}</div>
    {children}
  </div>
);

const Editable = ({ defaultValue, multiline, rows = 3 }) => (
  multiline
    ? <textarea defaultValue={defaultValue} rows={rows} className="inp" style={{ width:'100%', resize:'vertical', padding: 10, fontSize: 12.5, lineHeight: 1.55, fontFamily:'inherit' }}/>
    : <input defaultValue={defaultValue} className="inp" style={{ width:'100%', padding:'8px 10px' }}/>
);

const BriefEditor = ({ spec }) => (
  <div>
    <SpField label="Title"><Editable defaultValue={spec.title}/></SpField>
    <SpField label="One-liner"><Editable defaultValue={spec.summary}/></SpField>
    <SpField label="Problem statement">
      <Editable multiline rows={4} defaultValue="Motor claims under £2,500 take 6–9 days end-to-end, driving cost-to-serve up and NPS down. 78% of these claims have no fraud signal and could be auto-approved."/>
    </SpField>
    <SpField label="Proposed solution">
      <Editable multiline rows={5} defaultValue="Introduce a new adjud-engine service that consumes fraud-scorer output and auto-approves no-signal claims under the threshold. Existing payment-svc handles disbursement. Compliance review required for the auto-disbursement path."/>
    </SpField>
    <SpField label="Success metrics">
      <Editable multiline rows={3} defaultValue={'• Median cycle time for motor < £2.5k: 6d → < 4h\n• Auto-approval rate: 0% → 70%+\n• Customer-cost reduction: ~£18 per claim'}/>
    </SpField>
    <SpField label="Out of scope">
      <Editable multiline rows={2} defaultValue="Non-motor claim types. Claims above £2,500. Lending domain integration."/>
    </SpField>
    <div style={{ display:'flex', gap: 8, marginTop: 16 }}>
      <Btn variant="primary" icon="check">Save brief</Btn>
      <Btn icon="sparkle">Regenerate from request</Btn>
    </div>
  </div>
);

const PRDEditor = () => (
  <div>
    {['Goals','Non-goals','User stories','Functional requirements','Non-functional requirements','Rollout plan'].map(s => (
      <SpField key={s} label={s}>
        <Editable multiline rows={s.includes('requirements') ? 5 : 3} defaultValue={`${s} content — editable.`}/>
      </SpField>
    ))}
    <div style={{ display:'flex', gap: 8 }}>
      <Btn variant="primary" icon="check">Save PRD</Btn>
      <Btn icon="sparkle">Regenerate section</Btn>
    </div>
  </div>
);

const TechEditor = () => (
  <div>
    <SpField label="Architecture diagram">
      <div style={{ background:'#08101A', border:'1px solid var(--line)', borderRadius:5, padding:14, height: 160, display:'flex', alignItems:'center', justifyContent:'center' }}>
        <svg width="100%" height="100" viewBox="0 0 600 100">
          {[
            { x: 60,  l:'intake' },
            { x: 200, l:'fraud-scorer' },
            { x: 340, l:'adjud-engine', n:true },
            { x: 480, l:'payment-svc' },
          ].map((b,i) => (
            <g key={i}>
              <rect x={b.x-55} y={35} width="110" height="34" rx="4"
                fill={b.n ? 'rgba(59,130,246,0.15)' : 'var(--raised)'} stroke={b.n ? '#60A5FA' : 'var(--line-strong)'}/>
              <text x={b.x} y={56} textAnchor="middle" fontFamily="var(--mono)" fontSize="11" fill={b.n ? '#BFDBFE' : '#E5EAF2'}>{b.l}</text>
            </g>
          ))}
          {[[115,145],[255,285],[395,425]].map((p,i) => (
            <line key={i} x1={p[0]} y1={52} x2={p[1]} y2={52} stroke="#60A5FA" strokeWidth="1.4" markerEnd="url(#se-arrow)"/>
          ))}
          <defs><marker id="se-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10z" fill="#60A5FA"/></marker></defs>
        </svg>
      </div>
    </SpField>
    <SpField label="Data flows"><Editable multiline rows={4} defaultValue={'intake → fraud-scorer (RESTRICTED)\nfraud-scorer → adjud-engine (CONFIDENTIAL)\nadjud-engine → payment-svc (CONFIDENTIAL)\nadjud-engine → audit-svc (INTERNAL)'}/></SpField>
    <SpField label="API contract (adjud-engine)">
      <textarea rows={8} className="inp mono" style={{ width:'100%', fontSize: 11.5, padding: 10, fontFamily:'var(--mono)', resize:'vertical' }} defaultValue={`POST /v1/adjudicate
  body: { claimId, fraudScore, amount, evidence[] }
  → 200 { decision: APPROVE | DEFER, reason, traceId }
  → 4xx { error, code }

GET /v1/decisions/:traceId
  → 200 { decision, audit_chain_ref, decided_at }`}/>
    </SpField>
    <SpField label="Risks">
      <Editable multiline rows={3} defaultValue="• Auto-disbursement regulatory exposure — Compliance ADR required\n• payment-svc rate-limit at 80 req/s — capacity test before launch\n• Snowflake dependency — extend monitoring + runbook"/>
    </SpField>
    <div style={{ display:'flex', gap: 8 }}>
      <Btn variant="primary" icon="check">Save tech spec</Btn>
      <Btn icon="sparkle">Regenerate section</Btn>
    </div>
  </div>
);

const DecisionsList = () => (
  <div style={{ display:'flex', flexDirection:'column', gap: 10 }}>
    {[
      { d:'Use existing payment-svc rather than new payout-svc', who:'Maya Patel', when:'9m ago', tag:'ARCHITECTURE' },
      { d:'Threshold set at £2,500 (not £5,000)', who:'Robin Lee', when:'12m ago', tag:'PRODUCT' },
      { d:'Any fraud signal routes to human (no override)', who:'Nadia Iqbal', when:'15m ago', tag:'COMPLIANCE' },
      { d:'SLA: 95% < 4h, 100% < 24h', who:'Robin Lee', when:'15m ago', tag:'OPERATIONS' },
    ].map((d,i) => (
      <div key={i} className="card" style={{ padding: 12 }}>
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom: 4 }}>
          <span style={{ fontSize: 9.5, fontWeight: 600, color:'var(--blue-bright)', textTransform:'uppercase', letterSpacing:'0.06em' }}>{d.tag}</span>
          <span style={{ fontSize: 11, color:'var(--text-mute)' }}>{d.when}</span>
        </div>
        <div style={{ fontSize: 13 }}>{d.d}</div>
        <div style={{ fontSize: 11, color:'var(--text-mute)', marginTop: 4 }}>by {d.who}</div>
      </div>
    ))}
  </div>
);

const HistoryList = () => (
  <div>
    {[
      { t:'9m ago', a:'Spec Agent', m:'Generated brief, PRD, tech spec from Snappy Request' },
      { t:'8m ago', a:'Spec Agent', m:'Pulled stakeholder list from org graph' },
      { t:'7m ago', a:'Robin Lee',   m:'Confirmed threshold £2,500 and SLA targets' },
      { t:'6m ago', a:'Critic agent', m:'Flagged Compliance review for auto-disbursement' },
      { t:'5m ago', a:'Maya Patel',   m:'Confirmed payment-svc reuse' },
      { t:'2m ago', a:'Spec Agent',   m:'Regenerated tech spec with confirmed inputs' },
    ].map((h,i) => (
      <div key={i} style={{ display:'grid', gridTemplateColumns:'80px 1fr', gap: 10, padding:'8px 0', borderTop: i?'1px solid var(--line-soft)':'none', fontSize: 12 }}>
        <span style={{ color:'var(--text-mute)' }}>{h.t}</span>
        <div>
          <span style={{ color: h.a.includes('agent') || h.a === 'Spec Agent' ? 'var(--blue-bright)' : 'var(--text)' }}>{h.a}</span>
          <span style={{ color:'var(--text-dim)' }}> — {h.m}</span>
        </div>
      </div>
    ))}
  </div>
);

window.SpecsScreen = SpecsScreen;
